# Generated by Django 6.1.1 on 2026-09-12 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='memory', max_length=50, verbose_name='Ícone Material Symbols')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_percent', models.PositiveIntegerField(default=10, verbose_name='Percentual de Desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Chave de Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon', verbose_name='Cupom Aplicado')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Número do Pedido')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX Instantâneo (-15% OFF)'), ('CREDIT_CARD', 'Cartão de Crédito em até 10x'), ('BOLETO', 'Boleto Bancário')], default='PIX', max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Pagamento'), ('PAID', 'Pagamento Aprovado / Em Separação'), ('SHIPPED', 'Enviado / Em Trânsito'), ('DELIVERED', 'Entregue com Sucesso'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status do Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (R$)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frete (R$)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto (R$)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Cupom Utilizado')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Rastreio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca / Fabricante')),
                ('description', models.TextField(verbose_name='Descrição Completa')),
                ('technical_specs', models.JSONField(blank=True, default=dict, verbose_name='Especificações Técnicas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço a Prazo (R$)')),
                ('pix_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço à Vista no PIX (R$)')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Estoque Disponível')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem Principal')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Externa da Imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Vitrine')),
                ('is_hot_deal', models.BooleanField(default=False, verbose_name='Oferta Quente (HOT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Carrinho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Imagem')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Externa')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'slug'], name='store_produ_categor_48504b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_a0ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
